name: deploy kubernetes

on:
  push:
    branches:
      - main

jobs:
  update_deployment:
    name: update deployment
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Update deployment
      uses: ./
      with:
        server: ${{ secrets.K8S_SERVER }}
        ca_cert: ${{ secrets.K8S_CA_CERT }}
        token: ${{ secrets.K8S_TOKEN }}
        namespace: github-action
        templates: example/deployment01.yaml

    - name: Deploy Deployment with Custom Variables
      uses: ./
      env:
        INPUT_APP_NAME: nginx
      with:
        server: ${{ secrets.K8S_SERVER }}
        ca_cert: ${{ secrets.K8S_CA_CERT }}
        token: ${{ secrets.K8S_TOKEN }}
        namespace: github-action
        templates: example/deployment02.yaml

    - name: update deployment container image
      uses: ./
      with:
        server: ${{ secrets.K8S_SERVER }}
        ca_cert: ${{ secrets.K8S_CA_CERT }}
        token: ${{ secrets.K8S_TOKEN }}
        namespace: github-action
        deployment: nginx
        container: nginx
        image: nginx:1.24.0
