name: kubectl command

on:
  push:
    branches:
      - main

jobs:
  update_deployment:
    name: generate kubeconfig
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.8.0

      - name: check kubectl version
        run: |
          kubectl version -o yaml --client

      - name: get k8s info
        id: k8s_info
        run: |
          kubectl create namespace test-namespace
          kubectl apply -f example/serviceAccount.yaml
          echo K8S_SERVER=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.server}') >> $GITHUB_OUTPUT
          echo K8S_CA_CERT=$(kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}') >> $GITHUB_OUTPUT
          echo K8S_TOKEN=$(kubectl get secret deploy -n test-namespace -o jsonpath='{.data.token}' | base64 -d) >> $GITHUB_OUTPUT

      - name: generate kubeconfig
        uses: ./
        with:
          server: ${{ steps.k8s_info.outputs.K8S_SERVER }}
          ca_cert: ${{ steps.k8s_info.outputs.K8S_CA_CERT }}
          token: ${{ steps.k8s_info.outputs.K8S_TOKEN }}
          output: kubeconfig.yaml

      - name: get pods in test-namespace
        env:
          KUBECONFIG: kubeconfig.yaml
        run: |
          sudo chmod 644 kubeconfig.yaml
          kubectl apply -f example/deployment01.yaml
          kubectl get pods -n test-namespace
